<a href="https://colab.research.google.com/github/hiid0726/DataAnalysis/blob/main/hiid0726/ch05_01%2B02%EB%B3%B5%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np;


In [2]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [4]:
arr.ndim, arr.shape, type(arr)

(1, (5,), numpy.ndarray)

## 벡터화 연산

In [6]:
a = list(range(10))
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
a + 10;

TypeError: ignored

In [8]:
a * 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
a + [10]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [10]:
###### 리스트 타입은 벡터화 계산 위와 같이 안됨... 일괄로 계산 처리하려면 일단, 리스트컴프리헨션이 대안
[v +2 for v in a] ## 원소단위로 계산해보기...

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [13]:
arr = np.arange(10) ## == arr = np.array(range(10))
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
print(arr + 2); ## 각 원소에 계산진행
arr

[ 2  3  4  5  6  7  8  9 10 11]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
## 위의 산술연산이 이뤄지는 과정
arr + np.ones_like(arr) *2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [16]:
print(arr * 2);
arr

[ 0  2  4  6  8 10 12 14 16 18]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr >= 5 #(in 문과 비슷), bool로 이루어진 원소로 보여줌. == 5 인 원소들..

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [22]:
arr[arr >= 5] # True값에 해당되는 원소의 값들을 리턴

array([5, 6, 7, 8, 9])

In [25]:
#그럼 인덱스를 리턴해주는 건?
np.where(arr >= 5) # True에 해당하는 인덱스 리턴

(array([5, 6, 7, 8, 9]),)

In [26]:
arr2 = np.arange(0,10,2);
arr2


array([0, 2, 4, 6, 8])

In [29]:
arr2, arr2[arr2 >= 5], np.where(arr2 >= 5)
# 원본 배열, 배열 내 해당 값, 배열 내 해당 인덱스

(array([0, 2, 4, 6, 8]), array([6, 8]), (array([3, 4]),))

In [30]:
arr[(arr > 5) & (arr % 2 == 0)]

array([6, 8])

In [34]:
arr = np.array([
    (1,2,3,4), (5,6,7,8)
])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [36]:
t = np.array([
    [
        [1,2,3,4],[1,2,3,4]
    ],
    [
        [5,6,7,8], [5,6,7,8]
    ]

])
t

array([[[1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[5, 6, 7, 8],
        [5, 6, 7, 8]]])

In [37]:
t.ndim, t.shape

(3, (2, 2, 4))

In [41]:
a = np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [42]:
b = a
b[0,1] = 9
b, a

(array([[0, 9, 2, 3, 4],
        [5, 6, 7, 8, 9]]), array([[0, 9, 2, 3, 4],
        [5, 6, 7, 8, 9]]))

In [43]:
c = a.copy()
c[0,1] = 8;
c, a

(array([[0, 8, 2, 3, 4],
        [5, 6, 7, 8, 9]]), array([[0, 9, 2, 3, 4],
        [5, 6, 7, 8, 9]]))

In [45]:
a = np.arange(1,100,25)
a

array([ 1, 26, 51, 76])

In [50]:
a[3], a[-1], a[len(a)-1]

(76, 76, 76)

In [52]:
# 2차원 배열의 인덱싱
m = np.arange(6).reshape((2,3)) # 2,3 짜리 배열 생성
m

array([[0, 1, 2],
       [3, 4, 5]])

In [55]:
m[0,0], m[0,1], m[-2,-3]

(0, 1, 0)

In [ ]:
d1, d2 = m.shape #  == d1 = 행의 길이, d2 = 열의 길이

In [60]:
# 1차원 배열의 슬라이싱 = 리스트의 슬라이싱과 같다.
a[1:2]

array([26])

In [61]:
a2 = np.arange(0,100,10)
a2

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [62]:
a2[1:10:2] # 시작점, 끝점, 증가 폭 

array([10, 30, 50, 70, 90])

In [63]:
a2[10::-1] # 뒤집기

array([90, 80, 70, 60, 50, 40, 30, 20, 10,  0])

In [64]:
a2[::-1] # 뒤집기

array([90, 80, 70, 60, 50, 40, 30, 20, 10,  0])

In [65]:
m

array([[0, 1, 2],
       [3, 4, 5]])

In [66]:
m[0,:], m[0]

(array([0, 1, 2]), array([0, 1, 2]))

In [67]:
m[:,0], m[:,0:1]

(array([0, 3]), array([[0],
        [3]]))

## 배열의 자료형

In [69]:
x = np.array([1,2,3])
x.dtype

dtype('int64')

In [70]:
x = np.array([1.1,2,3])
x.dtype

dtype('float64')

In [72]:
x = np.array([1,2,3,4], dtype='i')
print(x, x.dtype)
x2 = np.array([1,2,3,4], dtype=int)
print(x2, x2.dtype)


[1 2 3 4] int32
[1 2 3 4] int64


In [73]:
x = np.array([1,2,3,4], dtype='f')
print(x, x.dtype)
x2 = np.array([1,2,3,4], dtype=float)
print(x2, x2.dtype)

[1. 2. 3. 4.] float32
[1. 2. 3. 4.] float64


In [75]:
a = np.zeros(5);
b = np.array([0,1,0,1,0])
a / b, b/a  ## 0을 0으로 나눴을때 오류는 안나고 nan으로 표시함., 반대로 0으로 1을 나눳을때 inf(infinity)로 표현된다.


<ipython-input-75-24c45a2d8eb0>:3: RuntimeWarning: invalid value encountered in true_divide
  a / b, b/a  ## 0을 0으로 나눴을때 오류는 안나고 nan으로 표시함.
<ipython-input-75-24c45a2d8eb0>:3: RuntimeWarning: divide by zero encountered in true_divide
  a / b, b/a  ## 0을 0으로 나눴을때 오류는 안나고 nan으로 표시함.


(array([nan,  0., nan,  0., nan]), array([nan, inf, nan, inf, nan]))

In [76]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [77]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [79]:
a = np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [82]:
np.zeros_like(a)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [83]:
np.ones_like(a)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [85]:
np.empty((2,5))

array([[3.09244541e-316, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 1.74593452e+238],
       [1.68743752e+160, 2.10653618e-052, 5.20381578e-090,
        2.38384597e+180, 6.94087780e-310]])

In [86]:
np.linspace(10,100,5) # 시작점, 끝점 사이를 5로 나눈다!

array([ 10. ,  32.5,  55. ,  77.5, 100. ])

In [87]:
np.logspace(0.1, 1, 5) # log0.1부터 log1까지를 5등분

array([ 1.25892541,  2.11348904,  3.54813389,  5.95662144, 10.        ])

In [88]:
A = np.arange(1,7).reshape(2,3)
A

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
A.ndim, A.shape

(2, (2, 3))

In [90]:
A.T # .T = 전치 연산자. 행과 열을 전치한다.

array([[1, 4],
       [2, 5],
       [3, 6]])

In [92]:
A.flatten(), A.ravel() #한줄로 펼쳐준다

(array([1, 2, 3, 4, 5, 6]), array([1, 2, 3, 4, 5, 6]))