<a href="https://colab.research.google.com/github/hiid0726/DataAnalysis/blob/main/hiid0726/ch05_02%2B03%2B04%EB%B3%B5%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr1 = np.arange(1,4)
arr2 = np.arange(4,7)

In [5]:
np.concatenate([arr1, arr2, arr1, arr2]) # 여러개 붙이는 것도 가능 ^^

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

In [9]:
arr1 = arr1.reshape(3,1)
arr2 = arr2.reshape(3,1)
print(arr1, arr2)
np.concatenate([arr1, arr2], axis = 0)

[[1]
 [2]
 [3]] [[4]
 [5]
 [6]]


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [8]:
np.concatenate([arr1, arr2], axis = 1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [13]:
a1 = np.ones((2,3))
a2 = np.zeros((2,3))
np.hstack((a1,a2)) # 행기준

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [17]:
b1 = np.ones((2,3))
b2 = np.zeros((3,3))
np.vstack((b1,b2)) # 열기준

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
c1 = np.ones((3,4))
c2 = np.zeros((3,4))
np.dstack((c1,c2))

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

* 브로드캐스팅

In [20]:
# 브로드 캐스팅 : 크기가 작은 배열을 자동으로 반복확장하여 크기기ㅏ 큰 배열에 맞추는 방법
x = np.arange(5)
x + 1

array([1, 2, 3, 4, 5])

In [21]:
x + np.ones_like(x) + 1

array([2, 3, 4, 5, 6])

In [22]:
x + 10

array([10, 11, 12, 13, 14])

In [23]:
x + np.ones_like(x) *10

array([10, 11, 12, 13, 14])

In [24]:
x = np.vstack([range(7)[i:i+3] for in range(5)])
x

SyntaxError: ignored

In [ ]:
y = np.arange(5).reshape(-1,1)

In [25]:
x = np.arange(1,5)
np.sum(x), x.sum()

(10, 10)

In [27]:
# 기술통계
x = np.random.randint(-30,30,30)
x

array([-11, -17,   2,  26,  -1, -10,  19, -11, -18,   5,  16,  18, -29,
        -2, -27, -22,   9,   5,  21,  20,  -9,   7, -20, -15, -30,  11,
         3,  22,  29,  28])

In [28]:
len(x)

30

In [29]:
np.mean(x), x.mean() #평균

(0.6333333333333333, 0.6333333333333333)

In [30]:
np.var(x) #분산

316.29888888888894

In [35]:
np.std(x), x.std() #표준편차

(17.78479375446589, 17.78479375446589)

In [34]:
np.max(x), np.min(x) #최댓값, 최솟값

(29, -30)

In [36]:
np.median(x) #중앙값! , 만약 전체 길이가 짝수 개 일경우, 두 값의 평균을 가져온다. 

2.5

In [38]:
np.quantile(x,0), np.percentile(x,0) #최솟값

(-30, -30.0)

In [40]:
np.quantile(x,0.25), np.percentile(x,25) # 1사분위

(-14.0, -14.0)

In [41]:
np.quantile(x,0.5), np.percentile(x,50) # 중앙값, 2사분위

(2.5, 2.5)

In [42]:
np.quantile(x,0.75), np.percentile(x,75) # 3사분위

(17.5, 17.5)

In [43]:
np.quantile(x,1), np.percentile(x,100) # 최댓값, 4사분위

(29, 29.0)

In [44]:
# 난수발생
np.random.seed(0) # 이후 나오는 랜덤값들이 순서가 일치한다.


In [45]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [46]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
np.random.shuffle(x) #원본에 영향O, 원본 자체를 섞어준다.

In [48]:
x

array([3, 1, 8, 7, 9, 0, 6, 4, 2, 5])

In [49]:
np.random.choice(x,5,replace=False) #x배열안에 있는 값 중에 5개를 추출하고 비복원.

array([0, 8, 7, 9, 1])

In [51]:
np.random.choice(5,5,replace=False)

array([2, 3, 4, 1, 0])

In [53]:
np.random.choice(np.arange(1,45), 6, replace=False)

array([18, 35, 13, 22, 38, 44])

In [55]:
np.random.choice(np.arange(1,7),6, replace = True)

array([4, 1, 4, 6, 5, 2])

In [56]:
np.random.choice(np.arange(1,7),6, p = [0,0,0,0.6,0.2,0.2]) # 확률 지정

array([4, 5, 6, 5, 5, 6])

In [62]:
#가격이 1만원 주식
price = 10000
#일간 수익률 => 기댓값(평균) 0, 표준편차 1% = 0.01 (표준정규분포)
days = 250
daily_earning_rate = np.random.randn(days) / 100
#250일 동안의 주가를 무작위로 생성
#주가 -> 전일가격 * (1 + 당일 수익률)
price_arr = np.empty(days)
for i, v in enumerate(daily_earning_rate):
  price *= (1+v)
  price_arr[i] = price

price_arr

array([10007.99847348, 10083.33407793,  9956.5670707 ,  9985.4262979 ,
        9954.07355356,  9907.10619007,  9876.21624522,  9834.40503824,
        9941.51535628,  9953.2215632 ,  9934.57069062,  9942.72660985,
        9936.96279114,  9780.50064256,  9847.561748  ,  9896.06564036,
        9847.52863442,  9811.75247537,  9831.60290025,  9881.81537612,
        9849.49942917,  9894.78894141,  9859.90425243,  9773.66972271,
        9754.55282772,  9743.50915895,  9618.22859156,  9690.04752469,
        9517.9110426 ,  9478.15667636,  9469.12854548,  9545.4268498 ,
        9323.21431822,  9487.60005538,  9373.50486715,  9275.40916799,
        9198.76918475,  9139.77613426,  8942.19645321,  8932.99980582,
        8888.63192573,  8871.39197748,  9025.36200929,  8949.05873313,
        8824.0115611 ,  8804.40588467,  8725.4177464 ,  8721.8467493 ,
        8785.81681643,  8691.7292147 ,  8918.65923394,  9041.53105096,
        9065.69654095,  9130.55894024,  9106.29244425,  9113.55148844,
      

In [63]:
x = np.random.randint(1,10,100)
x

array([5, 2, 6, 1, 4, 7, 4, 1, 4, 7, 6, 2, 8, 4, 5, 8, 1, 4, 6, 7, 7, 8,
       5, 8, 3, 1, 2, 7, 6, 5, 9, 8, 9, 7, 2, 5, 9, 6, 2, 7, 3, 8, 6, 8,
       7, 7, 4, 4, 5, 5, 2, 4, 6, 2, 8, 6, 5, 3, 1, 9, 8, 2, 2, 2, 8, 5,
       9, 7, 2, 3, 9, 5, 8, 9, 9, 4, 3, 6, 7, 5, 6, 8, 1, 4, 6, 6, 8, 9,
       1, 3, 7, 6, 2, 6, 2, 3, 4, 1, 4, 1])

In [64]:
np.unique(x)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
np.unique(x, return_counts = True)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 9, 13,  7, 12, 11, 14, 12, 13,  9]))

In [67]:
np.unique(x, return_counts = True, return_index = True)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 3,  1, 24,  4,  0,  2,  5, 12, 30]),
 array([ 9, 13,  7, 12, 11, 14, 12, 13,  9]))

In [71]:
key, value = np.unique(x, return_counts = True)
print(key)
print(value)

[1 2 3 4 5 6 7 8 9]
[ 9 13  7 12 11 14 12 13  9]


In [72]:
#두개의 시퀀스를 인덱스 기반으로 묶어주는것 = zip
list(zip(key,value))

[(1, 9), (2, 13), (3, 7), (4, 12), (5, 11), (6, 14), (7, 12), (8, 13), (9, 9)]

In [73]:
dict(zip(key,value))

{1: 9, 2: 13, 3: 7, 4: 12, 5: 11, 6: 14, 7: 12, 8: 13, 9: 9}

In [75]:
dict(zip(*np.unique(x, return_counts=True))) # 위와 같다.

{1: 9, 2: 13, 3: 7, 4: 12, 5: 11, 6: 14, 7: 12, 8: 13, 9: 9}